project_roots:
- ~/Documents/Sanctum/
- ~/Documents/Home/
- ~/Documents/Work/
- ~/Documents/Work/Projects
- ~/Documents/Work/Students/
- ~/Documents/Work/Reviews-grants/
- ~/Documents/Work/Reviews-papers/
- ~/Documents/Work/Teaching/2025-2026/
- ~/Documents/Forge/
board:
  columns:
  - name: Plan
    tag: "Plan \U0001F4D0"
    colour: 4
  - name: Active
    tag: "Active \U0001F6A7"
    colour: 2
  - name: Analyse
    tag: "Analyse \U0001F50D"
    colour: 5
  - name: Write
    tag: "Write \u2712\uFE0F"
    colour: 6
  - name: Review
    tag: "Review \U0001F58D\uFE0F"
    colour: 7
  - name: Shipped
    tag: "Shipped \U0001F680"
    colour: 3
  - name: Paused
    tag: "Paused \u23F8\uFE0F"
    colour: 1
  meta_tags:
  - "URGENT \u26A0\uFE0F"
  - "Collab \U0001F91D"
  - "Student \U0001F393"
  tag_aliases:
    "4. Write \u2712\uFE0F": "Write \u2712\uFE0F"
    "paused \u23F8\uFE0F": "Paused \u23F8\uFE0F"
    "Paused \u23F8\uFE0E": "Paused \u23F8\uFE0F"
    "Plan \U0001F4A1": "Plan \U0001F4D0"
    "active \U0001F6A7": "Active \U0001F6A7"
    "Plan \u263C": "Plan \U0001F4D0"
    "Review \U0001F4DD": "Review \U0001F58D\uFE0F"
    "Paused \u23F8": "Paused \u23F8\uFE0F"
    "Edit \U0001F58D\uFE0F": "Review \U0001F58D\uFE0F"
    "3. Analyse \U0001F50D": "Analyse \U0001F50D"
gtd:
  contexts:
  - office
  - lab
  - campus
  - home
  - errands
  - shopping
  - writing
  - review
  - analysis
  - planning
  - deep-work
  - low-energy
  - email
  - slack
  - calls
  - computer
  - reading
  - watching
  - anywhere
  - agenda
  reminders_list: Forge
  calendar_name: Forge
workspace_tags:
- work
project_areas:
  research:
  - Apodemus RNA vax - BBSRC
  - Apodemus ageing - Tom's WT
  - Apodemus vaccine exWAGO
  - Apodemus-DTV_Vaccines
  - Apodemus-WMHV
  - Apodemus-vaccines
  - Apodemus-virome
  - Badgers
  - Beetles Jacob Moorad
  - Deer-stress
  - Lepto
  - Mus Ageing-Pol-III_BBSRC_2018
  - Mus-Hb_Nutrition
  - NERC-Birds_light_at_night
  - Oncho - Mannu WT
  - Oncho-MIRS-AI_Gates
  - Schisto-DRIVERS
  - Seaweed Biofouling
  - Sheep_Alied
  - Wild_Immunology
  - ZebraFinches_ageing
  - Mozzies - AcMedSci GCRF networking grant
  - Mozzies - Mosquito Scotland
  - Mozzies - VectorGrid-Africa
  - Mozzies Nutrition Emilie
  - Mozzies-AI_MIRS_Royal_Society
  - Viruses-ViralHostPredictor
  - Sunfish - NERC EOI
  teaching: []
  admin:
  - Collaborations
  - Studentships
  - Writing tips
terminal: auto
project_tag: "\U0001F525 Forge"
