import Foundation

/// Generates a read-only markdown summary of due tasks with links back to their source files.
public struct DueSummaryGenerator {

    /// Create a new summary generator.
    public init() {}

    /// A single due task with its display label and source file path.
    public struct Item {
        public let task: ForgeTask
        public let label: String
        public let sourcePath: String

        public init(task: ForgeTask, label: String, sourcePath: String) {
            self.task = task
            self.label = label
            self.sourcePath = sourcePath
        }
    }

    /// Write a markdown summary of due tasks to `due.md` in the given task files root.
    ///
    /// - Parameters:
    ///   - overdueTasks: Tasks whose due date has passed.
    ///   - dueTodayTasks: Tasks due today.
    ///   - upcomingTasks: Tasks due within the lookahead window.
    ///   - days: Lookahead window in days.
    ///   - taskFilesRoot: Root directory for task files (typically `Forge/tasks`).
    public func writeMarkdownSummary(
        overdueTasks: [Item],
        dueTodayTasks: [Item],
        upcomingTasks: [Item],
        days: Int,
        taskFilesRoot: String
    ) {
        let fm = FileManager.default
        do {
            try fm.createDirectory(atPath: taskFilesRoot, withIntermediateDirectories: true)
        } catch {
            fputs("Failed to ensure task files directory for due summary: \(error)\n", stderr)
            return
        }

        let outPath = (taskFilesRoot as NSString).appendingPathComponent("due.md")
        let baseDir = taskFilesRoot

        var lines: [String] = []
        lines.append("<!-- Auto-generated by Forge — edit tasks in their source files. -->")
        lines.append("")
        lines.append("# Due Tasks")
        lines.append("")

        let totalCount = overdueTasks.count + dueTodayTasks.count + upcomingTasks.count
        if totalCount == 0 {
            lines.append("No overdue or upcoming tasks in the next \(days) days.")
        } else {
            lines.append("Overdue and upcoming tasks in the next \(days) days, grouped by status.")
            lines.append("")

            func appendSection(title: String, items: [Item]) {
                guard !items.isEmpty else { return }
                lines.append("## \(title) (\(items.count))")
                lines.append("")
                for item in items {
                    let task = item.task
                    let relativePath = RollupGenerator.relativePath(from: baseDir, to: item.sourcePath)

                    var parts: [String] = []
                    parts.append("- \(task.text)")
                    if let due = task.dueDateString {
                        parts.append("— due \(due)")
                    }
                    parts.append("— [\(item.label)](\(relativePath))")
                    if let ctx = task.context {
                        parts.append("— @\(ctx)")
                    }
                    if let wait = task.waitingOn {
                        parts.append("— ⏳\(wait)")
                    }
                    if let rule = task.repeatRule {
                        parts.append("— ↻\(rule.serialise())")
                    }
                    parts.append("— `\(task.id)`")

                    lines.append(parts.joined(separator: " "))
                }
                lines.append("")
            }

            appendSection(title: "Overdue", items: overdueTasks)
            appendSection(title: "Due Today", items: dueTodayTasks)
            appendSection(title: "Upcoming", items: upcomingTasks)
        }

        let content = lines.joined(separator: "\n") + "\n"
        do {
            try content.write(toFile: outPath, atomically: true, encoding: .utf8)
        } catch {
            fputs("Failed to write due markdown summary: \(error)\n", stderr)
        }
    }
}
