import Foundation

/// Generates read-only project task summaries inside area markdown files.
///
/// Each area file gets a clearly-delimited rollup section at the bottom,
/// listing pending tasks from mapped projects with links to their TASKS.md.
/// The section is regenerated on each run; manual edits within it are lost.
public final class RollupGenerator {

    private let config: ForgeConfig
    private let forgeDir: String
    /// Root directory for area .md files. When nil, forgeDir is used.
    private let taskFilesRoot: String
    private let markdownIO: MarkdownIO

    /// Markers that delimit the auto-generated section.
    static let startMarker = "<!-- forge:rollup -->"
    static let endMarker = "<!-- /forge:rollup -->"

    public init(config: ForgeConfig, forgeDir: String, taskFilesRoot: String? = nil) {
        self.config = config
        self.forgeDir = forgeDir
        self.taskFilesRoot = taskFilesRoot ?? forgeDir
        self.markdownIO = MarkdownIO()
    }

    /// Summary of what the rollup pass touched.
    public struct RollupReport: Sendable {
        public var areasUpdated: Int = 0
        public var projectsLinked: Int = 0
        public var tasksLinked: Int = 0
    }

    /// Regenerate the rollup section in every area file that has mapped projects.
    public func generateAll() throws -> RollupReport {
        var report = RollupReport()
        let workspacePath = config.resolvedWorkspacePath

        for (areaID, projectNames) in config.projectAreas {
            guard !projectNames.isEmpty else { continue }

            let areaPath = (taskFilesRoot as NSString).appendingPathComponent("\(areaID).md")
            guard FileManager.default.fileExists(atPath: areaPath) else { continue }

            let entries = gatherProjectEntries(
                projectNames: projectNames, workspacePath: workspacePath, areaPath: areaPath
            )

            guard !entries.isEmpty else {
                try stripRollupSection(at: areaPath)
                continue
            }

            let section = renderSection(entries: entries)
            try writeRollupSection(section, to: areaPath)

            report.areasUpdated += 1
            report.projectsLinked += entries.count
            report.tasksLinked += entries.reduce(0) { $0 + $1.tasks.count }
        }

        return report
    }

    // MARK: - Data Gathering

    private struct ProjectEntry {
        let name: String
        let column: String?
        let relativePath: String
        let tasks: [ForgeTask]
        let pendingCount: Int
        let overdueCount: Int
        let deferredCount: Int
    }

    private func gatherProjectEntries(
        projectNames: [String], workspacePath: String, areaPath: String
    ) -> [ProjectEntry] {
        let areaDir = (areaPath as NSString).deletingLastPathComponent
        var entries: [ProjectEntry] = []

        for name in projectNames.sorted() {
            let projPath = (workspacePath as NSString).appendingPathComponent(name)
            let tasksPath = (projPath as NSString).appendingPathComponent("TASKS.md")

            guard FileManager.default.fileExists(atPath: tasksPath) else { continue }

            let tasks = (try? markdownIO.parseTasks(at: tasksPath, projectName: name)) ?? []
            let pending = tasks.filter { !$0.isCompleted }
            guard !pending.isEmpty else { continue }

            let column = resolveColumn(for: projPath)
            let relativePath = Self.relativePath(from: areaDir, to: tasksPath)

            entries.append(ProjectEntry(
                name: name,
                column: column,
                relativePath: relativePath,
                tasks: pending,
                pendingCount: pending.count,
                overdueCount: pending.filter(\.isOverdue).count,
                deferredCount: pending.filter(\.isDeferred).count
            ))
        }

        return entries
    }

    private func resolveColumn(for projectPath: String) -> String? {
        let tagStore = FinderTagStore()
        guard let tags = tagStore.readTagsIfAvailable(at: projectPath) else { return nil }
        for tag in tags {
            if let col = config.column(forTag: tag) {
                return col.name
            }
        }
        return nil
    }

    // MARK: - Rendering

    private func renderSection(entries: [ProjectEntry]) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"

        var lines: [String] = []
        lines.append(Self.startMarker)
        lines.append("")
        lines.append("## Project Tasks")
        lines.append("")
        lines.append("> Auto-generated by `forge rollup` — edit tasks in each project's TASKS.md.")
        lines.append("")

        for entry in entries {
            var heading = "### [\(entry.name)](\(entry.relativePath))"
            if let col = entry.column {
                heading += " · \(col)"
            }

            var counts: [String] = ["\(entry.pendingCount) pending"]
            if entry.overdueCount > 0 { counts.append("\(entry.overdueCount) overdue") }
            if entry.deferredCount > 0 { counts.append("\(entry.deferredCount) deferred") }
            heading += " — \(counts.joined(separator: ", "))"

            lines.append(heading)
            lines.append("")

            let sections: [ForgeTask.Section] = [.nextActions, .waitingFor]
            for section in sections {
                let sectionTasks = entry.tasks.filter { $0.section == section }
                guard !sectionTasks.isEmpty else { continue }

                for task in sectionTasks {
                    var parts: [String] = ["- [ ] \(task.text)"]

                    if task.isOverdue {
                        parts.append("**OVERDUE** \(task.dueDateString ?? "")")
                    } else if task.isDueToday {
                        parts.append("**TODAY**")
                    } else if let due = task.dueDateString {
                        parts.append("due \(due)")
                    }

                    if task.isDeferred, let d = task.deferDateString {
                        parts.append("deferred until \(d)")
                    }

                    if let ctx = task.context {
                        parts.append("@\(ctx)")
                    }

                    if let w = task.waitingOn {
                        parts.append("⏳\(w)")
                    }

                    if let rule = task.repeatRule {
                        parts.append("↻\(rule.serialise())")
                    }

                    lines.append(parts.joined(separator: " — "))
                }
            }

            lines.append("")
        }

        lines.append(Self.endMarker)
        return lines.joined(separator: "\n")
    }

    // MARK: - File Writing

    /// Replace the rollup section in an area file, or append it if absent.
    private func writeRollupSection(_ section: String, to path: String) throws {
        var content = try String(contentsOfFile: path, encoding: .utf8)

        if let startRange = content.range(of: Self.startMarker),
           let endRange = content.range(of: Self.endMarker) {
            let fullRange = startRange.lowerBound..<endRange.upperBound
            content.replaceSubrange(fullRange, with: section)
        } else {
            let trimmed = content.hasSuffix("\n") ? content : content + "\n"
            content = trimmed + "\n" + section + "\n"
        }

        try content.write(toFile: path, atomically: true, encoding: .utf8)
    }

    /// Remove the rollup section from an area file if no projects have tasks.
    private func stripRollupSection(at path: String) throws {
        var content = try String(contentsOfFile: path, encoding: .utf8)

        guard let startRange = content.range(of: Self.startMarker),
              let endRange = content.range(of: Self.endMarker) else { return }

        var removeStart = startRange.lowerBound
        if removeStart > content.startIndex {
            let before = content.index(before: removeStart)
            if content[before] == "\n" { removeStart = before }
        }

        content.removeSubrange(removeStart..<endRange.upperBound)
        content = content.trimmingCharacters(in: .newlines) + "\n"

        try content.write(toFile: path, atomically: true, encoding: .utf8)
    }

    // MARK: - Path Utilities

    /// Compute a relative path from one directory to another file.
    static func relativePath(from base: String, to target: String) -> String {
        let baseComponents = (base as NSString).pathComponents
        let targetComponents = (target as NSString).pathComponents

        var commonLength = 0
        for i in 0..<min(baseComponents.count, targetComponents.count) {
            if baseComponents[i] == targetComponents[i] {
                commonLength = i + 1
            } else {
                break
            }
        }

        let upCount = baseComponents.count - commonLength
        let ups = Array(repeating: "..", count: upCount)
        let remainder = targetComponents[commonLength...]

        return (ups + remainder).joined(separator: "/")
    }
}
