#!/bin/zsh
#
# Assemble Forge.app from a built forge-menubar binary (shared by build.sh and CI).
#
# Usage:
#   packaging/assemble_forge_app.sh <FORGE_DIR> <BIN_DIR> <OUTPUT_APP_PATH>
#
# Arguments:
#   FORGE_DIR      — repository root (reads Sources/ForgeCore/Version.swift)
#   BIN_DIR        — directory containing the `forge-menubar` executable
#   OUTPUT_APP_PATH — full path to the bundle to create (e.g. dist/Forge.app)
#
set -euo pipefail

FORGE_DIR="${1:?FORGE_DIR required}"
BIN_DIR="${2:?BIN_DIR required}"
OUTPUT_APP="${3:?OUTPUT_APP_PATH required}"

if [[ -z "$OUTPUT_APP" || "$OUTPUT_APP" == "/" || "${OUTPUT_APP##*.}" != "app" ]]; then
  echo "error: OUTPUT_APP must be a non-empty path ending in .app (got: '${OUTPUT_APP}')" >&2
  exit 1
fi

MENUBAR_BIN="$BIN_DIR/forge-menubar"
if [[ ! -f "$MENUBAR_BIN" ]]; then
  echo "error: forge-menubar not found at $MENUBAR_BIN" >&2
  exit 1
fi

FORGE_CLI_BIN="$BIN_DIR/forge"
if [[ ! -f "$FORGE_CLI_BIN" ]]; then
  echo "error: forge CLI not found at $FORGE_CLI_BIN" >&2
  exit 1
fi

VERSION_FILE="$FORGE_DIR/Sources/ForgeCore/Version.swift"
if [[ ! -f "$VERSION_FILE" ]]; then
  echo "error: Version.swift not found at $VERSION_FILE" >&2
  exit 1
fi

FORGE_VERSION=$(grep -o 'version = "[^"]*"' "$VERSION_FILE" | cut -d'"' -f2)

SPARKLE_KEY_FILE="$FORGE_DIR/packaging/sparkle_public_ed25519.key"
if [[ ! -f "$SPARKLE_KEY_FILE" ]]; then
  echo "error: Sparkle public key not found at $SPARKLE_KEY_FILE" >&2
  exit 1
fi
SPARKLE_PUBLIC_KEY="$(tr -d '[:space:]' < "$SPARKLE_KEY_FILE")"

# Appcast must stay in sync with CI (see packaging/SPARKLE_SIGNING.md).
SUFeedURL="https://raw.githubusercontent.com/SimonAB/forge/main/docs/appcast.xml"

SPARKLE_SRC="$BIN_DIR/Sparkle.framework"
if [[ ! -d "$SPARKLE_SRC" ]]; then
  echo "error: Sparkle.framework not found at $SPARKLE_SRC (SwiftPM should place it next to build products)" >&2
  exit 1
fi

CONTENTS="$OUTPUT_APP/Contents"
MACOS_DIR="$CONTENTS/MacOS"
RESOURCES="$CONTENTS/Resources"
TOOLS_DIR="$RESOURCES/bin"

rm -rf "$OUTPUT_APP"
mkdir -p "$MACOS_DIR" "$RESOURCES" "$TOOLS_DIR"

cp "$MENUBAR_BIN" "$MACOS_DIR/Forge"
chmod +x "$MACOS_DIR/Forge"

cp "$FORGE_CLI_BIN" "$TOOLS_DIR/forge"
chmod +x "$TOOLS_DIR/forge"

cp -R "$SPARKLE_SRC" "$MACOS_DIR/"

# Optional icon override (generated by build.sh).
ICON_SRC="$BIN_DIR/AppIcon.icns"
if [[ -f "$ICON_SRC" ]]; then
  cp "$ICON_SRC" "$RESOURCES/AppIcon.icns"
fi

cat > "$CONTENTS/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>Forge</string>
    <key>CFBundleDisplayName</key>
    <string>Forge</string>
    <key>CFBundleIdentifier</key>
    <string>com.forge.menubar</string>
    <key>CFBundleVersion</key>
    <string>${FORGE_VERSION}</string>
    <key>CFBundleShortVersionString</key>
    <string>${FORGE_VERSION}</string>
    <key>CFBundleExecutable</key>
    <string>Forge</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>LSMinimumSystemVersion</key>
    <string>14.0</string>
    <key>NSCalendarsUsageDescription</key>
    <string>Forge can read your Calendar to show upcoming events in the CLI.</string>
    <key>NSRemindersFullAccessUsageDescription</key>
    <string>Forge can read Apple Reminders lists matched to your projects, create missing lists, set list colour from the kanban column, and update one optional status reminder per list.</string>
    <key>NSRemindersUsageDescription</key>
    <string>Forge can read Apple Reminders lists matched to your projects, create missing lists, set list colour from the kanban column, and update one optional status reminder per list.</string>
    <key>NSAppleEventsUsageDescription</key>
    <string>Forge reads selected Mail messages so you can capture them to the inbox, and runs commands in your chosen terminal.</string>
    <key>NSServices</key>
    <array>
        <dict>
            <key>NSMenuItem</key>
            <dict>
                <key>default</key>
                <string>Capture to Forge Inbox</string>
            </dict>
            <key>NSMessage</key>
            <string>captureToForgeInbox</string>
            <key>NSPortName</key>
            <string>Forge</string>
            <key>NSSendTypes</key>
            <array>
                <string>public.utf8-plain-text</string>
                <string>NSStringPboardType</string>
                <string>public.file-url</string>
                <string>NSURLPboardType</string>
            </array>
            <key>NSRequiredContext</key>
            <dict/>
        </dict>
        <dict>
            <key>NSMenuItem</key>
            <dict>
                <key>default</key>
                <string>Capture Mail Message to Forge</string>
            </dict>
            <key>NSMessage</key>
            <string>captureMailToForgeInbox</string>
            <key>NSPortName</key>
            <string>Forge</string>
            <key>NSSendTypes</key>
            <array>
                <string>public.utf8-plain-text</string>
                <string>NSStringPboardType</string>
            </array>
            <key>NSRequiredContext</key>
            <dict>
                <key>NSAppName</key>
                <string>Mail</string>
            </dict>
        </dict>
    </array>
    <key>SUFeedURL</key>
    <string>${SUFeedURL}</string>
    <key>SUPublicEDKey</key>
    <string>${SPARKLE_PUBLIC_KEY}</string>
    <key>SUEnableAutomaticChecks</key>
    <true/>
    <key>SUScheduledCheckInterval</key>
    <integer>86400</integer>
</dict>
</plist>
PLIST

echo "Assembled $OUTPUT_APP (version $FORGE_VERSION)"
